### ISSUE TITLE
[BUG] java.nio.file.AccessDeniedException

### ISSUE THREAD

**Issue by aaron-j-andrews** [wayfair-contribs/sonarscanner-buildkite-plugin#85]
## Describe the bug
During sonar scan the following error occurs:
`java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /workdir/artifacts-tmp.eZNdNFTuCx`

## To Reproduce

```
  - label: ":sonarqube: Sonarcloud PR scan"
    if: |
      // Only run for PR builds
      build.pull_request.id != null &&
        build.branch != "master"
    plugins:
      - ssh://git@github.com/wayfair-contribs/sonarscanner-buildkite-plugin.git#v0.1.1:
          sonarqube_host: https://sonarcloud.io
          project_key: <project key>
          sources: src
          artifacts: coverage-reports/*.xml
          enable_pull_request_scan: true
          uses_community_edition: false
          additional_flags:
            - -Dsonar.python.version=3.9
            - -Dsonar.python.coverage.reportPaths=coverage-reports/coverage-report.xml
            - -Dsonar.python.xunit.reportPath=coverage-reports/test-report.xml
            - -Dsonar.tests=tests
            - -Dsonar.organization=<org name>
            - -Dsonar.pullrequest.key=$BUILDKITE_PULL_REQUEST
            - -Dsonar.pullrequest.branch=$BUILDKITE_BRANCH
            - -Dsonar.pullrequest.base=$BUILDKITE_PULL_REQUEST_BASE_BRANCH
    soft_fail: # Ensures a Sonarqube error does not fail the pipeline
      - exit_status: "*"
    agents:
      queue: 'dev'
      build: 'true'
```

## Error

```
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: /workdir/artifacts-tmp.eZNdNFTuCx
--
  | at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:87)
  | at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)
  | at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
  | at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
  | at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  | at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  | at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
  | at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  | at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
  | at org.sonarsource.analyzer.commons.FileProvider.getMatchingFiles(FileProvider.java:45)
  | at org.sonar.plugins.python.PythonReportSensor.getReports(PythonReportSensor.java:73)
  | at org.sonar.plugins.python.coverage.PythonCoverageSensor.lambda$getCoverageReports$0(PythonCoverageSensor.java:93)
  | at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
  | at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  | at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  | at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  | at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
  | at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  | at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
  | at org.sonar.plugins.python.coverage.PythonCoverageSensor.getCoverageReports(PythonCoverageSensor.java:94)
  | at org.sonar.plugins.python.coverage.PythonCoverageSensor.execute(PythonCoverageSensor.java:77)
  | at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:62)
  | at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:75)
  | at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:48)
  | at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:66)
  | at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:48)
  | at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:64)
  | at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
  | at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
  | at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:466)
  | at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:462)
  | at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:418)
  | at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
  | at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
  | at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:130)
  | at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
  | at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
  | at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:58)
  | at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:52)
  | at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  | at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
  | at com.sun.proxy.$Proxy0.execute(Unknown Source)
  | at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
  | at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
  | at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
  | at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
  | at org.sonarsource.scanner.cli.Main.main(Main.java:61)
  | Caused by: java.nio.file.AccessDeniedException: /workdir/artifacts-tmp.eZNdNFTuCx
  | at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
  | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
  | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
  | at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
  | at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
  | at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
  | at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
  | at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83)
  | ... 50 more


```

## Additional information (if any)
I've logged into the container and the directory is present:

```
sh-4.4$ ls -la
total 116
drwxr-xr-x 1 sonar sonar   329 Oct 19 23:09 .
drwxr-xr-x 1 root  root      6 Oct 19 23:19 ..
drwxr-xr-x 3  2000  2000    45 Oct 19 23:07 .buildkite
-rw-r--r-- 1  2000  2000   102 Oct 19 23:07 .coveragerc
drwxr-xr-x 8  2000  2000   181 Oct 19 23:07 .git
drwxr-xr-x 2  2000  2000    24 Oct 19 23:07 .github
-rw-r--r-- 1  2000  2000   224 Oct 19 23:07 .gitignore
drwxr-xr-x 4 sonar sonar    48 Oct 19 23:13 .scannerwork
-rw-r--r-- 1  2000  2000  3768 Oct 19 23:07 Makefile
-rw-r--r-- 1  2000  2000  2566 Oct 19 23:07 README.md
drwx------ 2  2000  2000     6 Oct 19 23:07 artifacts-tmp.MxdhmwFYE7
drwxr-xr-x 2  2000  2000    38 Oct 19 23:07 build
drwxr-xr-x 2  2000  2000    56 Oct 19 23:07 coverage-reports
drwxr-xr-x 2  2000  2000    33 Oct 19 23:07 docs
-rw-r--r-- 1  2000  2000    92 Oct 19 23:07 envrc
-rw-r--r-- 1  2000  2000 88751 Oct 19 23:07 poetry.lock
-rw-r--r-- 1  2000  2000  1193 Oct 19 23:07 pyproject.toml
drwxr-xr-x 2  2000  2000   117 Oct 19 23:07 src
-rw-r--r-- 1  2000  2000  1109 Oct 19 23:07 setup.py
drwxr-xr-x 3  2000  2000    43 Oct 19 23:07 tests
sh-4.4$
```
