### ISSUE TITLE
Alternative to this action plus SonarCloud support

### ISSUE THREAD

**Issue by josh-bouganim-avant** [wayfair-contribs/sonarscanner-buildkite-plugin#95]
Hello,

As an alternative to this repo which is still in alpha and hasn't seen activity in a couple years, I was able to run the scan using the official docker image like so

```yaml
  - name: ":sonarcloud: SC Scan"
    plugins:
      - docker#v5.7.0:
          image: "sonarsource/sonar-scanner-cli:4"
          environment:
            - "SONAR_TOKEN=$SONAR_TOKEN"
            - "SONAR_HOST_URL=https://sonarcloud.io"
            - "SONAR_SCANNER_OPTS=-Dsonar.branch.name=$BUILDKITE_BRANCH -Dsonar.branch.target=$BUILDKITE_PULL_REQUEST_BASE_BRANCH"
```

and have a `sonar-project.properties` file in your root:
```
# Full set of options: https://docs.sonarcloud.io/advanced-setup/analysis-parameters/
# Required Properties
sonar.projectKey = *sc project key*
sonar.organization = *sc org*

# Optional Properties

sonar.projectName = *sc project name*
# See here for details how to setup file patterns: https://docs.sonarcloud.io/advanced-setup/analysis-scope/
sonar.sources = .
# exclude test files, auto-generated files here
sonar.exclusions = **/spec/**/*
sonar.tests = spec/
sonar.projectVersion = Initial
```
